### ISSUE TITLE
Comment out stub logos on people page

### ISSUE THREAD

**Issue by cthoyt** [earth-metabolome-initiative/earth-metabolome-initiative.legacy-website#7]
this page (https://www.earthmetabolome.org/people) has icons that don't have links that go anywhere for basically everyone at the moment. I would suggest the EMI takes care of the effort of finding this information for each person rather than asking each person to be proactive.

Further, I think you should remove the dead links, it's misleading and confusing

**Comment by oolonek** [comment]
Done. True that icons with deadlinks are useless. Like this it's also easier to track what remains to be completed.

We will contribute to adding these links when we can find them but it was intentionnally that we asked the EMI members to fill their info directly. Creating a github account is new for a good number but can be a great step to get people involved and eventually participate at places such as https://github.com/orgs/earth-metabolome-initiative/discussions. This is part of the Open Notebook Science approach we would like to follow. Of course it's clear not everyone will jump in and we will keep on adding on our side. But we will have asked. 
All this is also a kind of methodological experiment ... Let's see how it goes. In any case thanks for the feedback. This is the other important part (of implication and feedback) to build this initiative

**Comment by oolonek** [comment]
Removed inactive logos on peoples profiles and added emails. Will keep on adding by samll batches over time.
Let me know or feel free to reopen if your see alternatives to engage people and incentivate contribution on github .
